### ISSUE TITLE
RFC 9174 certificate profile SAN

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#1]
The certificate profile in RFC 9174 changed from the [earlier -26 draft](https://www.ietf.org/rfcdiff?url1=draft-ietf-dtn-tcpclv4-26&url2=rfc9174) in that the Subject Alternative Name changed from a URI to an otherName with ID `1.3.6.1.5.5.7.8.11 (id-on-bundleEID)`.

To generate CSR/certificate with this other name form using OpenSSL the syntax changes from `subjectAltName = URI:ipn:10.0` to `subjectAltName = otherName:1.3.6.1.5.5.7.8.11;IA5:ipn:10.0`. The encoded form is still an IA5String. On the verifying side, the entity needs to match the otherName type and specific `id-on-bundleEID` OID, then extract the IA5String value and compare with the expected URI.

**Comment by briantomko** [comment]
@BrianSipos thanks for your help on this.  This issue should now be resolved with merge of branch '70-tcpclv4-draft-to-rfc-updates'.  Just fyi, for now we support both the new rfc authentication method and the old draft authentication method.  The old draft authentication method prints out a warning to the user to update the certificates/keys.
