### ISSUE TITLE
Attribute `volatile` does not provide thread safety

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#10]
There are several places in HDTN where the `volatile` attribute keyword is used for variables which appear to be shared across multiple threads. The `volatile` attribute affects compiler optimization but [does _not_ guarantee thread safety](https://stackoverflow.com/questions/4557979/when-to-use-volatile-with-multi-threading) of the values. These should be made to either use `std::atomic<>` types or be guarded by a mutex (or equivalent barrier).

I noticed this specifically in the `LtpUdpEngine` but I suspect it is used elsewhere. In these cases the replacement of `volatile uint64_t ...` with `std::atomic<std::uint64_t>` would fix this issue.

**Comment by briantomko** [comment]
The volatile keyword is only used in hdtn usually on booleans to denote it is used by multiple threads, usually for a single writer thread and a single reader thread, and atomicity (such as multiple threads writing/incrementing) is not a concern.  There are many places where I'd like to use std::atomic or boost::atomic, but for each replacement, I want to determine the most appropriate "memory_order", as just declaring and using an atomic integer by default uses memory_order_seq_cst which is least efficient.  I hope to visit this issue soon when I learn more about the topic.

**Comment by briantomko** [comment]
This issue has been resolved by commit f72c1bfd40911f3208e2738ffd23269a9daa23bf

- All `volatile` variables, especially `volatile bool`, have been replaced with `std::atomic` with proper memory-ordering semantics.
- All convergence layer telemetry variables/counters use `std::atomic` with proper memory-ordering semantics.
