### ISSUE TITLE
CMake header install path and collisions

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#13]
The change for #8 does install headers but on a POSIX environment it clutters (and potentially collides with existing headers in) the main include directory (`/usr/local/include` or `/usr/include`) with all of the HDTN headers together.

Convention is to install headers under a library-named prefix directory to avoid potential collisions. Could this ticket be reopened and a solution worked out to install under `include/HDTN` or similar when `UNIX` is set? This could be a top-level logic to set some variable (e.g. `HDTN_INCLUDEDIR`) based on the platform and then use that variable for the `install()` destination.

There is also a way to use the [`PUBLIC_HEADER` property](https://cmake.org/cmake/help/v3.0/command/install.html) of a target to associate includes with a specific target, but this is not necessary here because this project isn't using export targets.

**Comment by briantomko** [comment]
This issue has been resolved with the merge of branch '76-cmake-custom-install-paths' into 'master'.
Added CMake cache variables CMAKE_INSTALL_LIBDIR (default "lib"), CMAKE_INSTALL_INCLUDEDIR (default "include/HDTN"), and CMAKE_INSTALL_BINDIR (default "bin").
For example, HDTN public headers will be installed to CMAKE_INSTALL_PREFIX/CMAKE_INSTALL_INCLUDEDIR/
Also I went ahead and utilized the CMake `PROPERTIES PUBLIC_HEADER` for include files to be installed.
