### ISSUE TITLE
Allow modifying the rate limit to a peer engine

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#16]
Can an API be added to the LtpEngine to change the rate limit after construction?

My use case involves dynamic rate limits (per peer ID) over time. The current API can set the initial rate but cannot (AFAICT) change without removing/adding the peer engine (which will interrupt all in-progress sessions).

**Comment by briantomko** [comment]
This issue has been resolved with the merge of branch 79-ltp-adjustable-rate-limiting into master.  The usage looks like:
```
ltpUdpEngineSrcPtr = ltpUdpEngineManagerSrcPtr->GetLtpUdpEnginePtrByRemoteEngineId(...);
//make sure ltpUdpEngineSrcPtr is not null (you created it through ltpUdpEngineManagerSrcPtr->AddLtpUdpEngine(...))
ltpUdpEngineSrcPtr->UpdateRate_ThreadSafe(700000000); //update rate to 700Mbit/sec (call whenever you like, even during active sessions)
```

As a side note: if you have simultaneous sessions to a peer, the "bundles" are likely to arrive out of order, especially if the bundle sizes are different.  I assume that's sort of expected with LTP/UDP.
