### ISSUE TITLE
Allow changing a peer engine address at runtime

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#27]
LTP itself does not bind a transfer session to a specific network address or UDP port; sessions are independent of how the segments arrive at the engine.

Currently it's not possible to alter the UDP endpoint of an `LtpUdpEngine` so to switch the network address of a peer engine it requires to remove the old `LtpUdpEngine` objects and create new ones. But this leaves a gap of service over time and also interrupts any sessions already in progress.

It would be better if the `LtpUdpEngine` provided a public interface to modify the `m_remoteEndpoint` member. It seems like that does not need to be synchronized with anything, since that endpoint is used only when sending outgoing datagrams.

As a prototype I attempted to add a public interface
```c++
void LtpUdpEngine::setEndpoint(const boost::asio::ip::udp::endpoint & remoteEndpoint)
```
as well as adding a public endpoint resolution function to the manager to be consistent with the engine construction
```c++
boost::asio::ip::udp::endpoint LtpUdpEngineManager::resolveEndpoint(const std::string & remoteHostname, const uint16_t remotePort)
```
and that seems to do the job. But I didn't do any extensive testing on this technique.

**Comment by briantomko** [comment]
This issue has been resolved by commit `c46c82c3`
New API:
```
void LtpUdpEngine::SetEndpoint_ThreadSafe(const boost::asio::ip::udp::endpoint& remoteEndpoint)
void LtpUdpEngine::SetEndpoint_ThreadSafe(const std::string& remoteHostname, const uint16_t remotePort)
```

This API also uses new functions if the UdpBatchSender is used:
```
void UdpBatchSender::SetEndpointAndReconnect_ThreadSafe(const boost::asio::ip::udp::endpoint& remoteEndpoint)
void UdpBatchSender::SetEndpointAndReconnect_ThreadSafe(const std::string& remoteHostname, const uint16_t remotePort)
```
I will close the issue when it is pushed.
