### ISSUE TITLE
Allow changing peer time delays at runtime

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#28]
Similar to #27 for address changes, it is necessary to be able to update the OWLT and margin for a peer. I have no need to modify these separately, so the interface would be something like:
```c++
void LtpEngine::SetDelays(const boost::posix_time::time_duration & oneWayLightTime, const boost::posix_time::time_duration & oneWayMarginTime)
```

It looks like this is a straightforward change to `LtpEngine` and `LtpTimerManager` classes to propagate the change down. This would affect only newly started sessions, but for my use case that's fine because the sessions are *very* short lived. A more extensive change may be needed if the goal is to change member variable state and to update running timers.

**Comment by briantomko** [comment]
This issue has been resolved by commit id `cabecb2d`.
The API is:
`void LtpEngine::SetDelays_ThreadSafe(const boost::posix_time::time_duration& oneWayLightTime, const boost::posix_time::time_duration& oneWayMarginTime, bool updateRunningTimers)`
I will close this issue as soon as it is pushed to the public github.
