### ISSUE TITLE
Multiple TX canceled callbacks are called if multiple cancel segments recevied

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#31]
The `LtpEngine` calls the callback set with `SetTransmissionSessionCancelledCallback()` multiple times per session if multiple "Cancel segment from the receiver" segments are received by the transmitting engine. This is causing bad behavior in my client which doesn't guard against these behaviors.

The API doesn't document either way, but it would be ideal if the actual `LtpEngine` interface would guarantee that exactly one of the completed or canceled callbacks was called per session (i.e. not both and and not more than one of either). This makes the logic of the client using the LTP engine simpler.

If this isn't possible the documentation should reflect the guarantees either way.

**Comment by briantomko** [comment]
This issue has been resolved by commit eb0d8b04.  Also added guards to prevent multiple ReceptionSessionCancelledCallback calls.  I added this to side branch 111-defer-reception-reports and will close the issue when it's merged into master.
