### ISSUE TITLE
Recommend to place large numbers of function parameters into a POD struct

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#32]
For some functions like `LtpUdpEngineManager::AddLtpUdpEngine()` and the related constructor for `LtpUdpEngine` there are very many parameters and it makes identifying which position corresponds with what parameter very difficult. In cases like this with many (more than ~4) parameters, it is helpful to follow a pattern to create a plain old data (POD) C++ struct (with its language-provided default constructor/assignment/copy operators) to use as a parameter container and then use a single (or significantly fewer) parameters to the actual functions.

For example, the above function (and its parameter) would look like:
```c++
struct LtpUdpEngineConfig {
  uint64_t thisEngineId = 0;
  uint64_t remoteEngineId = 0;
  ...
};

LtpUdpEngineManager::AddLtpUdpEngine(const LtpUdpEngineConfig &config) {
  ...
  auto newEngPtr = boost::make_unique<LtpUdpEngine>(config);
  ...
}
```
and using it would then be a more obvious matter of:
```c++
LtpUdpEngineConfig config;
// set parameters in any order and the name is obvious from this source
config.thisEngineId = ...
config.remotePort = ...
...
auto newEngPtr = engineManager->AddLtpUdpEngine(config);
...
```

It's important that the struct either have a default constructor or have default values for all fundamental-type values so that it's deterministic.

**Comment by briantomko** [comment]
This issue has been resolved by the merge of commit 583b13ff7d14fd9d5b67befea6206df137ca3ea1
