### ISSUE TITLE
Allow changing a peer MTU at runtime

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#33]
Unless there is a technical limitation preventing it, it would be helpful to allow changing the MTU (for segments and for reports) for a single peer at runtime. Similar to how the delay times can now be changed, it could be an option of whether the MTU change affects current sessions or just future sessions.

It appears that there is already an `LtpEngine::SetMtuReportSegment()` but nothing similar for data segment MTU. And the current function implicitly only applies to future sessions.

**Comment by briantomko** [comment]
This issue has been resolved by the merge of commit 3af27f287490f9d321bbeda3a98e1546c9189627
