### ISSUE TITLE
Installing HDTN on Raspberry Pi (Model B 8 GB RAM)

### ISSUE THREAD

**Issue by lolia-olu** [nasa/HDTN#45]
```
./runscript.sh: 12: ./build/common/bpcodec/apps/bpsink-async: not found
./runscript.sh: 19: ./build/module/hdtn_one_process/hdtn-one-process: not found
./runscript.sh: 24: ./build/common/bpcodec/apps/bpgen-async: not found

killing bpgen1...
./runscript.sh: 30: kill: No such process


killing egress...
./runscript.sh: 32: kill: No such process


killing bpsink2...
./runscript.sh: 34: kill: No such process
```
I ran ./runscript.sh and these are the errors I am receiving. I followed the HDTN video on NASA's website and did make install and looked at the READme  for ARM platforms.

Before running runscript, I did the sudo make install command, bc when I did 'make install' it gave me this error:
```
CMake Error at common/bpcodec/cmake_install.cmake:46 (file):
  file INSTALL cannot set permissions on "/usr/local/lib/libbpcodec.a":
  Operation not permitted.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)


make: *** [Makefile:100: install] Error 1

```

**Comment by lolia-olu** [comment]
HI Kyle, thank you for your response.
I followed those steps and received no errors during the make process. In another terminal in the HDTN directory I ran ./runscript.sh and it still gave me the same errors.

I then went into each directory where the error from my first comment arose and ran each command: 

**./build/common/bpcodec/apps/bpsink-async  --> and that worked**
```
[ bpsink   ][ info ]: This is HDTN version 1.0.0
[ bpsink   ][ warning]: notice: bpsink has no induct... bundle data will have to flow in through a bidirectional tcpcl outduct
[ bpsink   ][ info ]: starting..
[ bpsink   ][ info ]: Up and running
```

****./runscript.sh: 19: ./build/module/hdtn_one_process/hdtn-one-process --> said no directory found***
`bash: cd: hdtn-one-process: Not a directory`


**./runscript.sh: 24: ./build/common/bpcodec/apps/bpgen-async --> and that worked**
  ```
  ][ info ]: This is HDTN version 1.0.0
[ bpgen    ][ warning]: notice: bpgen has no outduct... bundle data will have to flow out through a bidirectional tcpcl induct
[ bpgen    ][ info ]: starting BpGenAsync..
[ bpgen    ][ info ]: Sending Bundles from BPGen Node 1 to final Destination Node 2
[ bpgen    ][ info ]: Waiting for Tcpcl opportunistic link on the induct to become available for forwarding bundles...
[ bpgen    ][ info ]: running bpgen for 0 seconds
[ bpgen    ][ info ]: BpGenAsync up and running
[ bpgen    ][ info ]: Waiting for Tcpcl opportunistic link on the induct to become available for forwarding bundles...

```

**Comment by kylevernyi** [comment]
Hi [lolia-olu](https://github.com/lolia-olu). Environmental variables are not shared between terminal instances. You can test to make sure that `HDTN_SOUCE_ROOT` is set by running the command `printenv HDTN_SOURCE_ROOT` or `echo $HDTN_SOURCE_ROOT`.

**Comment by lolia-olu** [comment]
It's working now. I followed the YouTube tutorial, so now looking for the hyperlink.
Thank you
