### ISSUE TITLE
No configuration control over static/shared libraries

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#6]
All of the HDTN libraries are currently unconditionally built as static libraries. It would be more convenient as a user if HDTN followed the standard CMake pattern of using a [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) project option to control this. The default option can be `OFF` to retain the current behavior.

**Comment by briantomko** [comment]
Currently, shared libs are unsupported as our internal libraries violate the rule of "passing STL containers across the DLL boundary".  The option could be added, but that would require the user to know that the shared library code was built using exactly the same compiler and compiler options/switches as the program that intends to use these shared libraries.

**Comment by BrianSipos** [comment]
Right now changing the mode is invasive (requires editing the CMake config files).

Even just defining the option as below and removing the specific `add_library(... STATIC ...)` would let me override the default for my use without needing to touch the CMake files.
```
option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
```

This default would keep the current behavior and the option is no more or less dangerous than for any other C++ library using templated classes.

**Comment by briantomko** [comment]
I will work on this issue now and let you know when it's pushed.  Thanks

**Comment by briantomko** [comment]
This issue has been resolved with the commit of 72-cmake-shared-lib-support into master

Please note the shared libraries caused a bug to appear, and so an API change had to be made from:
`static LtpUdpEngineManager * GetOrCreateInstance(const uint16_t myBoundUdpPort);`
to
`static std::shared_ptr<LtpUdpEngineManager> GetOrCreateInstance(const uint16_t myBoundUdpPort);`
