### ISSUE TITLE
No CMake runtime inspection to enable optimized function calls

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#7]
The single CMake option `USE_X86_HARDWARE_ACCELERATION` assumes that all of the related optimized C functions enabled by that option are both available and working on the target platform. In my case the target is a VM with an non-configurable CPU type, where some are available and some are not. This means I cannot enable the option and I lose some of the benefit of the functions that are available and working.

I recommend to use CMake to check the availability of individual optimized functions and then use separate preprocessor defines to enable/disable the use at a more fine grained level. I will add some comments with examples that I've briefly prototyped. I'm more focused on my own needs now, so won't dig to much into all of the possible combinations.

**Comment by BrianSipos** [comment]
These are the kinds of checks that can help make this more fine-grained:
```cmake
if(USE_X86_HARDWARE_ACCELERATION)
    add_compile_definitions(USE_X86_HARDWARE_ACCELERATION)
    if(NOT WIN32)
        SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -msse -msse2 -mbmi -mbmi2 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2")
    endif()

    check_symbol_exists(_pdep_u64 "immintrin.h" HAVE_pdep_u64)
    check_symbol_exists(_mm_crc32_u64 "immintrin.h" HAVE_mm_crc32_u64)
    check_symbol_exists(_bittest64 "immintrin.h" HAVE_bittest64)
    check_symbol_exists(_bittestandreset64 "immintrin.h" HAVE_bittestandreset64)
    check_symbol_exists(__andn_u64 "x86intrin.h" HAVE_andn_u64)
    if(HAVE_pdep_u64)
        add_compile_definitions(HDTN_USE_SDNV_FAST)
        add_compile_definitions(HDTN_USE_CBOR_FAST)
    endif(HAVE_pdep_u64)
    if(HAVE_mm_crc32_u64)
        add_compile_definitions(HDTN_USE_CRC32_FAST)
    endif(HAVE_mm_crc32_u64)
    if((HAVE_bittest64 AND HAVE_bittestandreset64) OR HAVE_andn_u64)
        add_compile_definitions(HDTN_USE_BITTEST)
    endif()
endif()
```

And then the various places that currently depend on only `USE_X86_HARDWARE_ACCELERATION` would be updated to use `HDTN_USE_SDNV_FAST` or similar fine-grained controls.

**Comment by briantomko** [comment]
I agree this definitely would be helpful, but it will need to be extended from "will it compile" to "will it run" on the machine.  If there is a way to run small compiled check programs to prevent an "Illegal instruction (core dumped)", that would be great.

**Comment by BrianSipos** [comment]
There is a CMake function [`try_run()`](https://cmake.org/cmake/help/latest/command/try_run.html) to use the exit code of a trial main entrypoint to detect working runtime behavior. This has issues with cross-compiling, but you can detect that and assume a working runtime in those cases (if the symbol exists).

So as a two-phase check that turns into a compile option:
1. Check that the symbol exists and set a `HAVE_xxx` variable
2. If the symbol exists and not cross-compiling, run a trial program using the function and set a `WORKING_xxx` variable.
3. Turn that into a `HAVE_xxx` compile definition.

**Comment by briantomko** [comment]
This issue has been resolved with the merge of branch '74-cmake-cpu-flag-detection' into 'master'
See the Readme titled "Optional X86 Hardware Acceleration" for an overview.
The details are implemented in the root directory in the file "hardware_acceleration.cmake".
The `check_symbol_exists` did not work for intrinsic functions, so a combination of `check_include_file`, `try_run`, `check_cxx_source_compiles`, and `check_cxx_source_runs `were used.
