### ISSUE TITLE
Cannot install HDTN libraries with CMake

### ISSUE THREAD

**Issue by BrianSipos** [nasa/HDTN#8]
The current CMake configuration is missing the necessary `install()` directives to get the runtime and development files from HDTN installed. This makes it difficult to use HDTN as a library dependency of an external project.

I have some prototyped patches that I have made to both:
1. Use generator expressions in the include paths following best practices of [modern CMake](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/)
2. Use install directives to install the built libraries and development files to the standard (system) paths. This also allows using standard techniques such as [DESTDIR](https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html) to control the install prefix.

**Comment by briantomko** [comment]
This issue has been resolved with the commit of 72-cmake-shared-lib-support into master

`make install` will now install to `CMAKE_INSTALL_PREFIX/[bin,lib,include]`
